# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LivePlayer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10LivePlayer.proto\"\x15\n\x05Types\x12\x0c\n\x04type\x18\x01 \x01(\t\" \n\x07Results\x12\x15\n\rresult_number\x18\x01 \x01(\x05\x32.\n\nLivePlayer\x12 \n\nLiveStream\x12\x06.Types\x1a\x08.Results\"\x00\x62\x06proto3')



_TYPES = DESCRIPTOR.message_types_by_name['Types']
_RESULTS = DESCRIPTOR.message_types_by_name['Results']
Types = _reflection.GeneratedProtocolMessageType('Types', (_message.Message,), {
  'DESCRIPTOR' : _TYPES,
  '__module__' : 'LivePlayer_pb2'
  # @@protoc_insertion_point(class_scope:Types)
  })
_sym_db.RegisterMessage(Types)

Results = _reflection.GeneratedProtocolMessageType('Results', (_message.Message,), {
  'DESCRIPTOR' : _RESULTS,
  '__module__' : 'LivePlayer_pb2'
  # @@protoc_insertion_point(class_scope:Results)
  })
_sym_db.RegisterMessage(Results)

_LIVEPLAYER = DESCRIPTOR.services_by_name['LivePlayer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TYPES._serialized_start=20
  _TYPES._serialized_end=41
  _RESULTS._serialized_start=43
  _RESULTS._serialized_end=75
  _LIVEPLAYER._serialized_start=77
  _LIVEPLAYER._serialized_end=123
# @@protoc_insertion_point(module_scope)
